### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by dolzhanskiyoa** [krasnoukhov/homeassistant-smart-maic#25]
MQTT installed, configured
Device Type: D101 G2
While adding device - Unknown error

**Comment by goodrasty** [comment]
така ж проблема

**Comment by goodrasty** [comment]
2024-12-27 20:21:44.648 ERROR (MainThread) [custom_components.smart_maic.config_flow] Unexpected exception 'NoneType' object has no attribute 'options'
Traceback (most recent call last):
  File "/config/custom_components/smart_maic/config_flow.py", line 95, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_maic/config_flow.py", line 58, in validate_input
    coordinator = SmartMaicCoordinator(smart_maic, hass)
  File "/config/custom_components/smart_maic/coordinator.py", line 39, in __init__
    self.set_update_interval()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/smart_maic/coordinator.py", line 44, in set_update_interval
    seconds=self.config_entry.options.get(EXPIRATION) or DEFAULT_EXPIRATION
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'options'

**Comment by goodrasty** [comment]
Дякую за швидке вирішення
